export const ADD_TASK_REQUEST = "ADD_TASK_REQUEST";
export const ADD_TASK_SUCCESS = "ADD_TASK_SUCCESS";
export const ADD_TASK_FAILURE = "ADD_TASK_FAILURE";


export const DELETE_TASK_REQUEST = "DELETE_SUBTASK_REQUEST";
export const DELETE_TASK_SUCCESS = "DELETE_SUBTASK_SUCCESS";
export const DELETE_TASK_FAILURE = "DELETE_SUBTASK_FAILURE";